param(
    [int]$Port = 18765,
    [switch]$KeepOnSuccess
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Stamp = Get-Date -Format "yyyyMMddHHmmss"
$SmokeRoot = Join-Path $RepoRoot "tmp\deploy-live-smoke-$Stamp"
$Workspace = Join-Path $SmokeRoot "workspace"
$ServiceDir = Join-Path $Workspace "live-smoke-service"
$GsaHome = $SmokeRoot
$GsaConfig = Join-Path $SmokeRoot ".gsa\config.yaml"
$GsaExe = Join-Path $RepoRoot "bin\gsa.exe"
$Started = $false
$Succeeded = $false

function Assert-SmokePath {
    param([string]$Path)
    $resolved = [System.IO.Path]::GetFullPath($Path)
    $tmpRoot = [System.IO.Path]::GetFullPath((Join-Path $RepoRoot "tmp"))
    if (-not $resolved.StartsWith($tmpRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refuse to clean path outside repo tmp: $resolved"
    }
}

function Invoke-Gsa {
    param([string[]]$GsaArgs)
    & $GsaExe @GsaArgs
    if ($LASTEXITCODE -ne 0) {
        throw "gsa failed: $($GsaArgs -join ' ')"
    }
}

function Wait-Health {
    param([string]$Url, [int]$Seconds = 30)
    $deadline = (Get-Date).AddSeconds($Seconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $response = Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 2
            if ($response.StatusCode -eq 200) {
                return
            }
        } catch {
            Start-Sleep -Milliseconds 500
        }
    }
    throw "health check did not become ready: $Url"
}

function Assert-HealthDown {
    param([string]$Url, [int]$Seconds = 10)
    $deadline = (Get-Date).AddSeconds($Seconds)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 1 | Out-Null
            Start-Sleep -Milliseconds 500
        } catch {
            return
        }
    }
    throw "health endpoint is still reachable after stop: $Url"
}

function Wait-NoProcess {
    param([int]$ProcessId, [int]$Seconds = 10)
    if ($ProcessId -le 0) {
        return
    }
    $deadline = (Get-Date).AddSeconds($Seconds)
    while ((Get-Date) -lt $deadline) {
        $process = Get-Process -Id $ProcessId -ErrorAction SilentlyContinue
        if ($null -eq $process) {
            return
        }
        Start-Sleep -Milliseconds 500
    }
    throw "process is still alive after stop: $ProcessId"
}

function Wait-DeleteSmokeRoot {
    param([string]$Path)
    Assert-SmokePath $Path
    for ($i = 0; $i -lt 10; $i++) {
        try {
            if (Test-Path -LiteralPath $Path) {
                Remove-Item -LiteralPath $Path -Recurse -Force
            }
            return
        } catch {
            Start-Sleep -Milliseconds 500
        }
    }
    throw "failed to clean smoke directory: $Path"
}

function Write-Utf8NoBom {
    param([string]$Path, [string]$Value)
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

try {
    if (-not (Test-Path -LiteralPath $GsaExe)) {
        throw "gsa.exe not found, build it first: $GsaExe"
    }

    New-Item -ItemType Directory -Force -Path (Join-Path $ServiceDir "cmd\server") | Out-Null
    New-Item -ItemType Directory -Force -Path (Split-Path $GsaConfig) | Out-Null

    Write-Utf8NoBom -Path (Join-Path $ServiceDir "go.mod") -Value @"
module live-smoke-service

go 1.25
"@

    Write-Utf8NoBom -Path (Join-Path $ServiceDir "cmd\server\main.go") -Value @"
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
)

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "$Port"
	}
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		_, _ = fmt.Fprint(w, "ok")
	})
	log.Printf("gsa-live-smoke started on :%s", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
"@

    $rootForYaml = $ServiceDir.Replace("\", "/")
    Write-Utf8NoBom -Path (Join-Path $ServiceDir "agent.generated.yaml") -Value @"
id: live-smoke-service
name: Live Smoke Service
description: temporary deploy live smoke service
type: imported-service
root: $rootForYaml
health:
  url: http://127.0.0.1:$Port/healthz
capabilities_endpoint:
  url: http://127.0.0.1:$Port/api/agent/capabilities
capabilities:
  - health
"@

    Write-Utf8NoBom -Path (Join-Path $ServiceDir "deploy.generated.yaml") -Value @"
runtime: go
confidence: high
build:
  command: go build ./...
run:
  command: go run ./cmd/server
ports:
  - name: http
    value: $Port
dependencies:
  - none-detected
env:
  - name: PORT
    required: false
health_check:
  path: /healthz
notes:
  - Temporary service generated by deploy_live_smoke.ps1.
"@

    $manifestPath = (Join-Path $ServiceDir "agent.generated.yaml")
    Write-Utf8NoBom -Path $GsaConfig -Value @"
version: 1
home: $GsaHome
workspace: $Workspace
llm:
  provider: none
  base_url:
  model:
  api_key_env: GSA_LLM_API_KEY
projects:
  - manifest: $manifestPath
"@

    $env:GSA_HOME = $GsaHome
    $env:GSA_CONFIG = $GsaConfig
    $env:GOCACHE = Join-Path $SmokeRoot ".gocache"

    Invoke-Gsa -GsaArgs @("deploy", "plan", "live-smoke-service")
    Invoke-Gsa -GsaArgs @("deploy", "status", "live-smoke-service")
    Invoke-Gsa -GsaArgs @("--mode", "full", "deploy", "start", "live-smoke-service", "--confirm")
    $Started = $true

    $healthUrl = "http://127.0.0.1:$Port/healthz"
    Wait-Health -Url $healthUrl -Seconds 45

    $statusOutput = & $GsaExe "deploy" "status" "live-smoke-service"
    if ($LASTEXITCODE -ne 0 -or ($statusOutput -join "`n") -notmatch "status:\s+running") {
        throw "deploy status did not report running:`n$($statusOutput -join "`n")"
    }

    $logsOutput = & $GsaExe "deploy" "logs" "live-smoke-service" "--tail" "80"
    if ($LASTEXITCODE -ne 0 -or ($logsOutput -join "`n") -notmatch "gsa-live-smoke started") {
        throw "deploy logs did not contain startup line:`n$($logsOutput -join "`n")"
    }

    $statePath = Join-Path $SmokeRoot ".gsa\services\live-smoke-service.json"
    $stateText = Get-Content -LiteralPath $statePath -Raw -Encoding UTF8
    if ($stateText -notmatch '"pid"\s*:\s*(\d+)') {
        throw "failed to read pid from state file: $statePath"
    }
    $servicePid = [int]$Matches[1]

    Invoke-Gsa -GsaArgs @("--mode", "full", "deploy", "stop", "live-smoke-service", "--confirm")
    $Started = $false
    Assert-HealthDown -Url $healthUrl -Seconds 15
    Wait-NoProcess -ProcessId $servicePid -Seconds 15

    $Succeeded = $true
    Write-Host "LIVE_DEPLOY_SMOKE_OK"
} finally {
    if ($Started) {
        try {
            & $GsaExe "--mode" "full" "deploy" "stop" "live-smoke-service" "--confirm" | Out-Host
        } catch {
            Write-Warning "cleanup stop failed: $_"
        }
    }

    if ($Succeeded -and -not $KeepOnSuccess) {
        Wait-DeleteSmokeRoot -Path $SmokeRoot
        Write-Host "cleaned: $SmokeRoot"
    } else {
        Write-Host "smoke workspace preserved: $SmokeRoot"
    }
}
